### ISSUE TITLE
Data Wrangling

### ISSUE THREAD

**Issue by akshat02** [open-source-society/data-science#18]
Hi
I'm currently a Udacity Data Analyst Nanodegree student. One of the tougher projects that I encountered recently was that of data munging and wrangling. As New York Times also noted once, the data wangling part can take 50-80% of a data scientist's time in data science projects. So I thought it should be important for people to get their data wrangling skills on par as well when learning data science. 
If you'd like you can include the following course under a new 'Data Wrangling' section - 
[Data Wrangling with MongoDB](https://www.udacity.com/course/data-wrangling-with-mongodb--ud032)

Or maybe any other courses from EdX, Coursera or elsewhere.

Thanks
Akshat Tickoo

**Comment by royshouvik** [comment]
@akshat02 [Data Wrangling course](https://www.udacity.com/course/data-wrangling-with-mongodb--ud032) from Udacity looks good for the topic. I am not very interested in a Coursera course, since they have made free access to the courses very limited. If you see any other good course on the topic we can add them later, but for now it would be nice if you can send in a PR with your suggested change.. Thanks 👍 and happy learning.
